### ISSUE TITLE
Present station_model on Station Map

### ISSUE THREAD

**Issue by ThomDietrich** [weewx/website#4]
Hey there,
a typical station on the station map is presented with these data points:

![image](https://user-images.githubusercontent.com/2870104/120940982-7cb43d80-c720-11eb-8231-88dd2e8c8a70.png)

Data like description, lat/lon and station_type is shown. However, on both sides of the registration

* https://github.com/weewx/weewx/blob/dc4a38bc311bc837cb5b2c33ebf5f30d1b636216/bin/weewx/restx.py#L1521
* https://github.com/weewx/website/blob/2634732c4225d3e8804aa02ee7b27cc837a6ff21/register/register.cgi#L126

the additional data point `station_model` is communicated and stored.

For `station_type` "Interceptor" or "FineOffsetUSB" it would be interesting to show the `station_model`, especially as it is already in the database.

Is there a clear reason why you decided against that? I would otherwise suggest to include `station_model` as part of the view from the screenshot above.

**Comment by matthewwall** [comment]
implemented at commit ec2a52e

**Comment by ThomDietrich** [comment]
Nice! Confirmed working. Thanks :)
